[tool.poetry]
name = "gnn"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "gnn"}]

[tool.poetry.dependencies]
python = "^3.9,<=3.11"
networkx = "^3.2.1"
numpy = "^1.26.4"
pandas = "^2.2.1"
scipy = "^1.12.0"
scikit-learn = "^1.4.1.post1"
tensorflow = "^2.15.0.post1"
keras = "^3.0.5"
pydantic = "^2.6.2"


[tool.poetry.group.dev.dependencies]
epc = "^0.0.5"
pytest = "^7.4.4"
ipykernel = "^6.29.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = ".venv"

[tool.black]
line-length = 105

[tool.isort]
skip = ["gnn"]