[tool.poetry]
name = "gnn"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "gnn"}]

[tool.poetry.dependencies]
python = "^3.9,<=3.11"
networkx = "^3.2.1"
numpy = "^1.26.2"
pandas = "^2.1.3"
scipy = "^1.11.4"
scikit-learn = "^1.3.2"
tensorflow = "^2.15.0"


[tool.poetry.group.dev.dependencies]
epc = "^0.0.5"
pytest = "^7.4.3"
ipykernel = "^6.27.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = ".venv"

[tool.black]
line-length = 105

[tool.isort]
skip = ["gnn"]